import { Room } from '../types/room';

export const mockRooms: Room[] = [
  {
    id: '1',
    hotelId: '1',
    namaKamar: 'Superior Twin',
    stokKamar: 3,
    hargaKamar: 1000000,
    rating: 4.3,
    image: require('../assets/images/Hotel_Satu.png'),
    statusText: 'Tersedia 3 kamar lagi!',
    statusColor: '#7B22D3',
  },
  {
    id: '2',
    hotelId: '1',
    namaKamar: 'Deluxe Double',
    stokKamar: 1,
    hargaKamar: 1000000,
    rating: 4.0,
    image: require('../assets/images/Hotel_Dua.png'),
    statusText: 'Kamar terbatas',
    statusColor: '#7B22D3',
  },
  {
    id: '3',
    hotelId: '1',
    namaKamar: 'Superior Queen',
    stokKamar: 2,
    hargaKamar: 1000000,
    rating: 4.2,
    image: require('../assets/images/Hotel_Tiga.png'),
    statusText: 'Kamar Terbatas',
    statusColor: '#7B22D3',
  },
  {
    id: '4',
    hotelId: '1',
    namaKamar: 'Executive Queen',
    stokKamar: 5,
    hargaKamar: 1000000,
    rating: 4.1,
    image: require('../assets/images/Hotel_Satu.png'),
    statusText: 'Tersedia',
    statusColor: '#7B22D3',
  },
]; 